# Generated by Django 5.0.6 on 2024-05-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="biography",
            field=models.TextField(blank=True, null=True),
        ),
    ]
